package com.systemmonitor.features.profile.presentation.devices

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Computer
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material.icons.filled.PhoneAndroid
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.ViewModel
import dagger.hilt.android.lifecycle.HiltViewModel
import javax.inject.Inject

@HiltViewModel
class MyDevicesViewModel @Inject constructor() : ViewModel()

@Composable
fun MyDevicesScreen(
    viewModel: MyDevicesViewModel = hiltViewModel(),
    onBackClick: () -> Unit
) {
    var showAddDeviceDialog by remember { mutableStateOf(false) }
    var selectedDeviceToRemove by remember { mutableStateOf<String?>(null) }
    var newDeviceName by remember { mutableStateOf("") }

    val bgGradient = Brush.verticalGradient(colors = listOf(Color(0xFF080C16), Color(0xFF0B132B), Color(0xFF070B18)))

    Box(modifier = Modifier.fillMaxSize().background(bgGradient)) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(16.dp)
                .verticalScroll(rememberScrollState())
        ) {
            Row(modifier = Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
                IconButton(onClick = onBackClick) {
                    Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back", tint = Color.White)
                }
                Spacer(modifier = Modifier.width(8.dp))
                Column {
                    Text("My Devices", color = Color.White, fontSize = 20.sp, fontWeight = FontWeight.Bold)
                    Text("Manage connected laptops, phones & active sessions", color = Color(0xFF94A3B8), fontSize = 12.sp)
                }
            }

            Spacer(modifier = Modifier.height(20.dp))

            // Add Device Header Button
            Button(
                onClick = { showAddDeviceDialog = true },
                colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF00E5FF)),
                shape = RoundedCornerShape(12.dp),
                modifier = Modifier.fillMaxWidth().height(48.dp)
            ) {
                Icon(Icons.Default.Add, contentDescription = null, tint = Color.Black)
                Spacer(modifier = Modifier.width(8.dp))
                Text("Pair New Device", color = Color.Black, fontWeight = FontWeight.Bold)
            }

            Spacer(modifier = Modifier.height(20.dp))

            Text("Connected Devices (3)", color = Color.White, fontSize = 15.sp, fontWeight = FontWeight.Bold)
            Spacer(modifier = Modifier.height(12.dp))

            DeviceItemTile("Work Laptop (Dell XPS 15)", "Windows 11 Pro • 192.168.1.108", "Connected", true) { selectedDeviceToRemove = "Work Laptop" }
            Spacer(modifier = Modifier.height(10.dp))
            DeviceItemTile("Primary Phone (Samsung S24)", "Android 14 • 192.168.1.42", "This Device", false) { selectedDeviceToRemove = "Samsung S24" }
            Spacer(modifier = Modifier.height(10.dp))
            DeviceItemTile("Home Workstation (Custom PC)", "Windows 10 • 192.168.1.150", "Offline", false) { selectedDeviceToRemove = "Home Workstation" }
        }

        // Add Device Dialog
        if (showAddDeviceDialog) {
            AlertDialog(
                onDismissRequest = { showAddDeviceDialog = false },
                containerColor = Color(0xFF0F172A),
                title = { Text("Pair New Device", color = Color.White, fontWeight = FontWeight.Bold) },
                text = {
                    Column {
                        Text("Enter 6-digit Pairing Code generated by Windows Agent:", color = Color(0xFF94A3B8), fontSize = 13.sp)
                        Spacer(modifier = Modifier.height(12.dp))
                        OutlinedTextField(
                            value = newDeviceName,
                            onValueChange = { newDeviceName = it },
                            placeholder = { Text("e.g. 784-902", color = Color(0xFF64748B)) },
                            colors = OutlinedTextFieldDefaults.colors(focusedTextColor = Color.White, unfocusedTextColor = Color.White, focusedBorderColor = Color(0xFF00E5FF), unfocusedBorderColor = Color(0xFF1E293B)),
                            modifier = Modifier.fillMaxWidth()
                        )
                    }
                },
                confirmButton = {
                    Button(onClick = { showAddDeviceDialog = false }, colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF00E5FF))) {
                        Text("Connect", color = Color.Black, fontWeight = FontWeight.Bold)
                    }
                },
                dismissButton = {
                    TextButton(onClick = { showAddDeviceDialog = false }) {
                        Text("Cancel", color = Color(0xFF94A3B8))
                    }
                }
            )
        }

        // Remove Device Dialog
        if (selectedDeviceToRemove != null) {
            AlertDialog(
                onDismissRequest = { selectedDeviceToRemove = null },
                containerColor = Color(0xFF0F172A),
                title = { Text("Remove Device", color = Color.White, fontWeight = FontWeight.Bold) },
                text = { Text("Are you sure you want to remove '${selectedDeviceToRemove}'? Active sessions will be terminated.", color = Color(0xFF94A3B8), fontSize = 13.sp) },
                confirmButton = {
                    Button(onClick = { selectedDeviceToRemove = null }, colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFEF4444))) {
                        Text("Remove Device", color = Color.White, fontWeight = FontWeight.Bold)
                    }
                },
                dismissButton = {
                    TextButton(onClick = { selectedDeviceToRemove = null }) { Text("Cancel", color = Color(0xFF94A3B8)) }
                }
            )
        }
    }
}

@Composable
private fun DeviceItemTile(name: String, details: String, status: String, isOnline: Boolean, onRemoveClick: () -> Unit) {
    Surface(
        modifier = Modifier.fillMaxWidth().border(1.dp, Color(0xFF1E293B), RoundedCornerShape(16.dp)),
        shape = RoundedCornerShape(16.dp),
        color = Color(0xFF0F172A).copy(alpha = 0.85f)
    ) {
        Row(
            modifier = Modifier.padding(16.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Box(
                    modifier = Modifier.size(44.dp).clip(CircleShape).background(if (isOnline) Color(0xFF10B981).copy(alpha = 0.15f) else Color(0xFF64748B).copy(alpha = 0.15f)),
                    contentAlignment = Alignment.Center
                ) {
                    Icon(if (name.contains("Laptop") || name.contains("PC")) Icons.Default.Computer else Icons.Default.PhoneAndroid, contentDescription = null, tint = if (isOnline) Color(0xFF10B981) else Color(0xFF64748B))
                }
                Spacer(modifier = Modifier.width(14.dp))
                Column {
                    Text(name, color = Color.White, fontSize = 15.sp, fontWeight = FontWeight.Bold)
                    Text(details, color = Color(0xFF94A3B8), fontSize = 11.sp)
                }
            }
            Row(verticalAlignment = Alignment.CenterVertically) {
                Text(status, color = if (isOnline) Color(0xFF10B981) else Color(0xFF64748B), fontSize = 12.sp, fontWeight = FontWeight.Bold)
                Spacer(modifier = Modifier.width(8.dp))
                IconButton(onClick = onRemoveClick) {
                    Icon(Icons.Default.Delete, contentDescription = "Remove", tint = Color(0xFFEF4444), modifier = Modifier.size(20.dp))
                }
            }
        }
    }
}
