package com.systemmonitor.navigation

sealed class NavDestination(val route: String) {
    object Home : NavDestination("home")
    object DeviceCenter : NavDestination("device_center")
    object AddLaptop : NavDestination("add_laptop")
    object PairLaptop : NavDestination("pair_laptop")
    object LaptopDetails : NavDestination("laptop_details")
    object Processes : NavDestination("processes")
    object RemoteControl : NavDestination("remote_control")
    object ScreenViewer : NavDestination("screen_viewer")
    object SecurityCenter : NavDestination("security_center")
    object NetworkCenter : NavDestination("network_center")
    object FileCenter : NavDestination("file_center")
    object AppLock : NavDestination("app_lock")
    object ChooseLockMethod : NavDestination("choose_lock_method")
    object SetPin : NavDestination("set_pin")
    object LockResult : NavDestination("lock_result")
    object AppUsage : NavDestination("app_usage")
    object UsageDetails : NavDestination("usage_details")
    object UsageAnalytics : NavDestination("usage_analytics")
    object DigitalWellbeing : NavDestination("digital_wellbeing")
    object ParentalControl : NavDestination("parental_control")
    object Reports : NavDestination("reports")
    object Alerts : NavDestination("alerts")
    object Settings : NavDestination("settings")
    object SettingsSecurity : NavDestination("settings_security")
    object SettingsNotifications : NavDestination("settings_notifications")
    object SettingsPower : NavDestination("settings_power")
    object SettingsScreen : NavDestination("settings_screen")
    object SettingsMonitoring : NavDestination("settings_monitoring")
    object SettingsDevice : NavDestination("settings_device")
    object SettingsRemote : NavDestination("settings_remote")
    object SettingsPrivacy : NavDestination("settings_privacy")
    object SettingsReports : NavDestination("settings_reports")
    object SettingsBackup : NavDestination("settings_backup")
    object SettingsAdvanced : NavDestination("settings_advanced")
    object SettingsAbout : NavDestination("settings_about")
    object Profile : NavDestination("profile")
    object EditProfile : NavDestination("edit_profile")
    object ProfileUpdated : NavDestination("profile_updated")
    object Login : NavDestination("login")
    object Register : NavDestination("register")
}
