package com.systemmonitor.navigation

sealed class NavDestination(val route: String) {
    object Home : NavDestination("home")
    object DeviceCenter : NavDestination("device_center")
    object AddLaptop : NavDestination("add_laptop")
    object PairLaptop : NavDestination("pair_laptop")
    object LaptopDetails : NavDestination("laptop_details")
    object Processes : NavDestination("processes")
    object RemoteControl : NavDestination("remote_control")
    object ScreenViewer : NavDestination("screen_viewer")
    object SecurityCenter : NavDestination("security_center")
    object NetworkCenter : NavDestination("network_center")
    object FileCenter : NavDestination("file_center")
    object AppLock : NavDestination("app_lock")
    object SetPin : NavDestination("set_pin")
    object AppUsage : NavDestination("app_usage")
    object DigitalWellbeing : NavDestination("digital_wellbeing")
    object ParentalControl : NavDestination("parental_control")
    object Reports : NavDestination("reports")
    object Alerts : NavDestination("alerts")
    object Settings : NavDestination("settings")
    object Profile : NavDestination("profile")
    object Login : NavDestination("login")
    object Register : NavDestination("register")
}
